### ISSUE TITLE
'VGG' object has no attribute 'conv3'

### ISSUE THREAD

**Issue by outouser** [GorkaAbad/Sniper-Backdoor#1]
Hi, when I run the code, I get this error “AttributeError: 'VGG' object has no attribute 'conv3'”，the error is in File "/home/xyq/tmp/Sniper_backdoor/participants.py", line 168, in extract_latent_space
    hook = client.model.conv3.register_forward_hook(my_hook)

**Comment by GorkaAbad** [comment]
Hi,
I just committed a fix aa422cf.
Could you please try again?
Thanks

**Comment by outouser** [comment]
thanks for your help
